Feature/add consumer tests
aslishemesh/fox_consumer pull request #4
Opened 2017-05-07 12:10 UTC by aslishemesh

* Fox consumer class tests
* Fox DB (postgres) class tests
* update sql queries syntax

@caduri plz review.

2017-05-09 15:46 UTC, caduri requested changes
Nice work 👍

2017-05-09 15:46 UTC, caduri commented on fox_consumer/fox_helper.py
>      schema = {
dont forget to remove the bullshit properties

2017-05-09 15:46 UTC, caduri commented on fox_consumer/fox_helper.py
> +            json_data = json.loads(data)
verify json should get a json not a string

2017-05-09 15:46 UTC, caduri commented on fox_consumer/fox_helper.py
> +            json_item = json.loads(json_obj)
this should be before calling to verify_json

2017-05-09 15:46 UTC, caduri commented on tests/fox_consumer_postgress_tests.py
> +    # TODO - ASLI - learn and use "side affect"
remove comments

2017-05-09 15:46 UTC, caduri commented on tests/fox_consumer_postgress_tests.py
> +        self.fox_db.connect_to_postgres()
you should have tests for `connect_to_postgres` as well

2017-05-09 15:46 UTC, caduri commented on tests/fox_consumer_postgress_tests.py
> +    def test_save_item_with_exist_item(self,  mock_is_item_exist):
typo `test_save_item_with_existing_item`

2017-05-09 15:46 UTC, caduri commented on tests/fox_consumer_postgress_tests.py
> +        self.fox_db.db_cursor.execute.assert_called_with(sql_update)
Nice :)

2017-05-09 15:46 UTC, caduri commented on tests/fox_consumer_postgress_tests.py
> +    def test_save_item_with_non_exist_item(self, mock_is_item_exist):
existing

2017-05-09 15:46 UTC, caduri commented on tests/fox_consumer_postgress_tests.py
> +    def test_is_item_exist_with_exist(self):
what do you test here, I don't understand the function name...

2017-05-09 15:46 UTC, caduri commented on tests/fox_consumer_postgress_tests.py
> +    def test_is_item_exist_with_exist(self):
call it `test_is_item_exist_with_existing_item`

2017-05-09 15:46 UTC, caduri commented on tests/fox_consumer_postgress_tests.py
> +        self.fox_db.is_item_exist(item)
where is the test for the return value

2017-05-09 15:46 UTC, caduri commented on tests/fox_consumer_postgress_tests.py
> +    def test_is_item_exist_with_non_exist(self):
same

2017-05-09 15:46 UTC, caduri commented on tests/fox_consumer_postgress_tests.py
> +        self.fox_db.is_item_exist(item)
same

2017-05-09 15:46 UTC, caduri commented on tests/fox_consumer_tests.py
> +    @patch('fox_consumer.PostgresWrapper')          # 'override' the entire object
why do you need to mock this?

2017-05-09 15:46 UTC, caduri commented on tests/fox_consumer_tests.py
> +    def test_runner(self, mock_runner, mock_start_consumer, mock_initialize_rabbitmq):
better name `test_runner_verify_calling_methods`

2017-05-09 17:23 UTC, aslishemesh commented on tests/fox_consumer_tests.py
> +    @patch('fox_consumer.PostgresWrapper')          # 'override' the entire object
because I don't need to test anything about the PostgresWrapper.
(the PostgresWrapper is just another attribute in the Consumer class...)

2017-05-10 12:43 UTC, caduri commented on tests/fox_consumer_postgress_tests.py
> +        self.fox_db.db_cursor.fetchone.return_value = (True,1)
why do you need a tuple?

2017-05-14 07:26 UTC, aslishemesh commented on tests/fox_consumer_postgress_tests.py
> +        self.fox_db.db_cursor.fetchone.return_value = (True,1)
since the method "fetchone" return a tuple.

2018-09-23 07:59 UTC, closed without merging